### ISSUE TITLE
Add social banner opengraph image

### ISSUE THREAD

**Issue by chrisrabe** [tindrew/redot-landing-page#20]
# Description

When you share the URL, we want a banner image to show up

# Design

Use the following image below as the opengraph image banner:

![Image](https://github.com/user-attachments/assets/78138b66-109d-438d-9890-58a83a2f8454)

**Comment by opdev1004** [comment]
Related to #33 #31 Can we decide whether we just want image or designed from vue template.

**Comment by chrisrabe** [comment]
Closing this issue. Making #31 as the main thread
